language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"
sudo: false
install:
  - pip install --upgrade setuptools pip pytest pytest-cov
  - pip install .
  - python -m exam_kernel.install --sys-prefix
addons:
  sonarcloud:
    organization: "digiklausur"
    token:
      secure: mVuDTIxgLA2iKlEsUgoKXlDV7v8wHzlOICe0DWc2h4YB/dYbemiwkNemfGeTl7GVg5Ntbn2EVYbJ7MhTtyo0/B/ZRerqu1vFQz2M1XquoT05FiYDSN7ElKu36fBdBrsmS11KWiwYVKRqrgeHBPFT59ypiiaFiAhxssdAaj3rjULih7CrOlM2UvXTvhd33C/aW/IwtRzLb94E7hjvMe3Rj8hCrD5ZuwhP3FUfV0/zCnE9ad6SHPpBteBOt//Zjk2yzdtI1UmVjoHQ4XBRMx1RNWokH6oqAnxmvJ6oewrRwB/a1tFiXrn3XnV9GPqoUeRzzCw0tzo7RhhH3pRdoeqKs5CDlSE2ezLrt+s6iU63/DYlURBQg6wiK0L798PbmuzrExvGtZqIl8rtStHWAkOahTWnkZfNPdqvRSPohmj812ZipX2KJ4qYQ20B9neyXRfbeG9RSiKwbn9MPcbzoECxX5ZReznUpJSDkMVXmUf7PnP1Irr/DTprQdcsCK0w0reuv+bZAwi6UWcuYfLXxi57PwDrZaNc4MHOu7i8KAtv5KPOWz0s/fk+PYKZixXxhOBKjb/O+nPBzt07IWPg5bWN8zitRm/h3e2FiTeIdL1+C+nF5zhAu6lpgyE6cS2Y4hHasW2B3vky4Vj+tKWSVMGVpnbYq6AQsJh3Wv8ea6qJv2Q=
script:
  - py.test --cov exam_kernel -v --cov-report xml
  - sonar-scanner