language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"
sudo: false
install:
  - pip install --upgrade setuptools pip pytest pytest-cov
  - pip install .
  - python -m exam_kernel.install --sys-prefix
addons:
  sonarcloud:
    organization: "digiklausur"
    token: ${SONAR_TOKEN}
script:
  - py.test --cov exam_kernel -v --cov-report xml
  - sonar-scanner