language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"
sudo: false
install:
  - pip install --upgrade setuptools pip pytest pytest-cov
  - pip install .
  - python -m exam_kernel.install --sys-prefix
addons:
  sonarcloud:
    organization: "digiklausur"
    token:
      secure: "GOkfAlVFl+nuhAdU60akutHm4b3doeZmEjywfQ6qF3seQ5YRDj9MBuSnybKGfuRjGFQZI9iSj9nZJO0x9zY0rlKbK3Pr9db+MZaML3ukaCvWo+0Oih9g3pxTPukrz3liQJcnalFDTTqrA5dc/ZypWdYn8/9WvDcMKTUs45l4gg0CrS4Pn46+HuPw5uIjtLpiZn/Bp3p0Qp14CpXAraghDEmAIL+qDbVDaLCf0HnznZWp41Tr0SsPDNiMSvBWyXvlxwROyv2PTmXwsgCi6PJLtdZQtcdp+xblfkwZHvvdi4pJ6zLhQAt3v8qm+ODbVbSZkWSfoekx9iQvlHTxuN2bmQa/ZQ8eEANVtNgQ3DE92hHPEg8WzhUuxm/EBoWDCTfoH4AyK1ln352RgJ4QVKk8NdAZDIwROyOqYQcrKeKYQVc8fI8m02U21FDUx5RmDGA/eMfJvUuLZCfZmqHPJ5jFFhfUmF3Gq8kHq1975PUBVxHrm3rbjvwVRRmY4JtPhTKAto3argd7ggnA/ECHOna3QEE/jAgYySQtAYgEM+kBbXpjh1Fhqn8Dk2fcztoyuxyRPcoOjdc5Idb7xFe2o7koFdD0+FZKGHqS1KK48HPuuhTrNUsKXqKq0PRMxo2VINEqcC5Bd2/RYe9rU3rmDMh+TuckKgR9fqLeDNxxIji+rhU="
script:
  - py.test --cov exam_kernel -v --cov-report xml
  - sonar-scanner
