language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"
sudo: false
install:
  - pip install --upgrade setuptools pip pytest pytest-cov
  - pip install .
  - python -m exam_kernel.install --sys-prefix
addons:
  sonarcloud:
    organization: "digiklausur"
    token: "b+iCwqYD5RV9XfU4cukE+QMrM4cTF1b6OTGcht0N8/6pyL6apqklbKLWGVdWXmnp0rijCYZsaQ3C8E9JodmXoHcbDNqCr2wvg73jSZiv3FOoBxRwmD90nQR7yxTK3v+PSprAQfq6nOidTu6v15kZSfrYxwcw4AjtOuPY8pMNVcjF23rh1fPoYUlJ5TQVFsUonW+jBlXptGjZdBqReMqnQ7XR8iyQjPBj1nRoTTbVvEZDpvrVvheLkK9oxEKeuhSQ9FUqoDEzA66ntX+ZzC9MLCzP7zMSrabU7CRvSAgMdmgcZCk/Rw0dtRBiFJaFzfTdL6mqhJ4cI1Z1PwDwvv/Y88xJbfX6ivr43+VMvGclYPNFFmu7hhT1tyHLhNRzvaUQvj0AeXXf01D0eSrZLAEH7x86ZKUXe7YLbriTg6TIeJ079eN3RMNFZ6tcnTGwi+9Id+orYFMuAWGOkHsRmcqCYV5Ncum6JxmhNol5WsyeuwCzFR8JWTQuzt+gcOO8DM/ozQXiAhM5J6L1FFVOTXMEQg17cUtiQDdc+tjnowLZsqG5025Dl7h7lRV8SNBNaX2MVdsSq4CmMrJZAUC6KPF3PcgU6i80SGLwhlKQ81wOnrpdx2kD79WxV0+PpXMDyHMiqXhNizdtehqseu/NvkL2/RhUc0zMKTSgVgwIr7TyLCw="
script:
  - py.test --cov exam_kernel -v --cov-report xml
  - sonar-scanner
